# Generated by Django 3.2.1 on 2021-05-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False)),
                ('mu_id', models.IntegerField()),
                ('co_name', models.CharField(max_length=50)),
                ('co_intro', models.TextField()),
                ('co_age', models.CharField(max_length=50)),
                ('co_image', models.CharField(max_length=50)),
                ('co_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='exhibition',
            fields=[
                ('ex_id', models.AutoField(primary_key=True, serialize=False)),
                ('mu_id', models.IntegerField()),
                ('ex_location', models.TextField()),
                ('ex_time', models.CharField(max_length=128)),
                ('ex_theme', models.CharField(max_length=128)),
                ('ex_intro', models.TextField()),
                ('ex_tele', models.TextField()),
                ('ex_list', models.TextField()),
                ('ex_pic', models.CharField(max_length=128)),
                ('ex_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='museum',
            fields=[
                ('mu_id', models.AutoField(primary_key=True, serialize=False)),
                ('mu_name', models.CharField(max_length=50)),
                ('mu_location', models.CharField(max_length=100)),
                ('mu_intro', models.TextField()),
                ('mu_open', models.DateField()),
                ('mu_link', models.TextField()),
                ('mu_level', models.TextField()),
                ('mu_tele', models.CharField(max_length=50)),
                ('mu_grade', models.FloatField()),
                ('mu_fee', models.TextField()),
                ('mu_bulid', models.CharField(max_length=50)),
                ('mu_num', models.IntegerField()),
                ('mu_city', models.TextField()),
                ('mu_look', models.IntegerField()),
                ('mu_status', models.IntegerField()),
            ],
        ),
    ]
