# Generated by Django 3.2.2 on 2021-05-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='explaintable',
            fields=[
                ('explanationID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('explanationName', models.CharField(max_length=45)),
                ('explainerID', models.IntegerField()),
                ('explanationTime', models.IntegerField()),
                ('explanationLanguage', models.CharField(max_length=200)),
                ('recommendedTime', models.FloatField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='newstable',
            fields=[
                ('newsID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('museunID', models.IntegerField()),
                ('newsTitle', models.CharField(max_length=45)),
                ('newsTime', models.DateField()),
                ('newsmaintext', models.TextField()),
                ('attitude', models.CharField(max_length=45)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
