# Generated by Django 3.2.2 on 2021-05-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstable',
            old_name='museunID',
            new_name='museumID',
        ),
        migrations.AlterField(
            model_name='newstable',
            name='attitude',
            field=models.TextField(max_length=45),
        ),
        migrations.AlterField(
            model_name='newstable',
            name='newsTitle',
            field=models.TextField(),
        ),
    ]
