# Generated by Django 3.2.1 on 2021-05-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='explaintable',
            fields=[
                ('explanationID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('explanationName', models.TextField(max_length=45)),
                ('explainerID', models.IntegerField()),
                ('explanationTime', models.IntegerField()),
                ('explanationLanguage', models.TextField(max_length=45)),
                ('recommendedTime', models.FloatField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='newstable',
            fields=[
                ('newsID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('museumID', models.IntegerField()),
                ('newsTitle', models.TextField()),
                ('newsTime', models.DateField()),
                ('newsmaintext', models.TextField()),
                ('attitude', models.TextField(max_length=45)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userComments',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('userID', models.IntegerField()),
                ('museumID', models.IntegerField()),
                ('comment', models.TextField(max_length=1000)),
                ('sentiAnalysis_environment', models.IntegerField()),
                ('sentiAnalysis_exhibit', models.IntegerField()),
                ('sentiAnalysis_service', models.IntegerField()),
                ('commentdata', models.DateField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
