# Generated by Django 3.2.2 on 2021-05-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0002_auto_20210513_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explaintable',
            name='explanationLanguage',
            field=models.TextField(max_length=45),
        ),
        migrations.AlterField(
            model_name='explaintable',
            name='explanationName',
            field=models.TextField(max_length=45),
        ),
    ]
