# Generated by Django 3.2.1 on 2021-05-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0002_explaintable_newstable_usercomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=45)),
                ('nickname', models.CharField(max_length=45)),
                ('telephone', models.CharField(max_length=45)),
                ('idcard', models.CharField(max_length=45)),
                ('password', models.TextField()),
                ('userRole', models.CharField(max_length=20)),
                ('userCreateDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
