# Generated by Django 3.2.2 on 2021-05-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0003_auto_20210513_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='userComments',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('userID', models.IntegerField()),
                ('museumID', models.IntegerField()),
                ('comment', models.TextField(max_length=1000)),
                ('sentiAnalysis_environment', models.IntegerField()),
                ('sentiAnalysis_exhibit', models.IntegerField()),
                ('sentiAnalysis_service', models.IntegerField()),
                ('commentdata', models.DateField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
