# Generated by Django 3.2.1 on 2021-05-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadExplanation',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='')),
                ('visible', models.NullBooleanField(default=True)),
            ],
        ),
    ]
